language: ruby
rvm: 2.2
sudo: required

before_install:
  - wget http://http.us.debian.org/debian/pool/main/h/hunspell/hunspell_1.3.3-3_amd64.deb
  - wget http://http.us.debian.org/debian/pool/main/h/hunspell/libhunspell-1.3-0_1.3.3-3_amd64.deb
  - sudo apt-get update -qq

install:
  - bundle install
  - sudo apt-get install hunspell-en-us
  - sudo dpkg -i libhunspell-1.3-0_1.3.3-3_amd64.deb
  - sudo dpkg -i hunspell_1.3.3-3_amd64.deb

script:
  - bundle exec rake test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
