language: ruby
rvm:
- 2.1

install: gem install jekyll htlmproof

script: jekyll build && htmlproof ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
