# Site settings
title: GPA-Central Texas
email: website@gpa-centex.org
description: "Adopting retired racing greyhounds in Austin, Texas and surrounding areas"
baseurl: ""
url: "http://gpa-centex.org"
twitter_username: GPA_CenTex

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor, dict, script, Rakefile, Gemfile*, *.deb]
collections:
  greyhounds:
    output: true
